// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file proto/crypto-stream.proto (package crypto_stream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Request to add a ticker
 *
 * @generated from message crypto_stream.AddTickerRequest
 */
export class AddTickerRequest extends Message<AddTickerRequest> {
  /**
   * e.g., "BTCUSD", "ETHUSD"
   *
   * @generated from field: string ticker = 1;
   */
  ticker = "";

  constructor(data?: PartialMessage<AddTickerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.AddTickerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ticker", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddTickerRequest {
    return new AddTickerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddTickerRequest {
    return new AddTickerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddTickerRequest {
    return new AddTickerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddTickerRequest | PlainMessage<AddTickerRequest> | undefined, b: AddTickerRequest | PlainMessage<AddTickerRequest> | undefined): boolean {
    return proto3.util.equals(AddTickerRequest, a, b);
  }
}

/**
 * @generated from message crypto_stream.AddTickerResponse
 */
export class AddTickerResponse extends Message<AddTickerResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<AddTickerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.AddTickerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddTickerResponse {
    return new AddTickerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddTickerResponse {
    return new AddTickerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddTickerResponse {
    return new AddTickerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AddTickerResponse | PlainMessage<AddTickerResponse> | undefined, b: AddTickerResponse | PlainMessage<AddTickerResponse> | undefined): boolean {
    return proto3.util.equals(AddTickerResponse, a, b);
  }
}

/**
 * Request to remove a ticker
 *
 * @generated from message crypto_stream.RemoveTickerRequest
 */
export class RemoveTickerRequest extends Message<RemoveTickerRequest> {
  /**
   * @generated from field: string ticker = 1;
   */
  ticker = "";

  constructor(data?: PartialMessage<RemoveTickerRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.RemoveTickerRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ticker", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveTickerRequest {
    return new RemoveTickerRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveTickerRequest {
    return new RemoveTickerRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveTickerRequest {
    return new RemoveTickerRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveTickerRequest | PlainMessage<RemoveTickerRequest> | undefined, b: RemoveTickerRequest | PlainMessage<RemoveTickerRequest> | undefined): boolean {
    return proto3.util.equals(RemoveTickerRequest, a, b);
  }
}

/**
 * @generated from message crypto_stream.RemoveTickerResponse
 */
export class RemoveTickerResponse extends Message<RemoveTickerResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<RemoveTickerResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.RemoveTickerResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveTickerResponse {
    return new RemoveTickerResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveTickerResponse {
    return new RemoveTickerResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveTickerResponse {
    return new RemoveTickerResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveTickerResponse | PlainMessage<RemoveTickerResponse> | undefined, b: RemoveTickerResponse | PlainMessage<RemoveTickerResponse> | undefined): boolean {
    return proto3.util.equals(RemoveTickerResponse, a, b);
  }
}

/**
 * Request to start streaming prices
 *
 * Empty for now, may add filters later
 *
 * @generated from message crypto_stream.StreamPricesRequest
 */
export class StreamPricesRequest extends Message<StreamPricesRequest> {
  constructor(data?: PartialMessage<StreamPricesRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.StreamPricesRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamPricesRequest {
    return new StreamPricesRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamPricesRequest {
    return new StreamPricesRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamPricesRequest {
    return new StreamPricesRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamPricesRequest | PlainMessage<StreamPricesRequest> | undefined, b: StreamPricesRequest | PlainMessage<StreamPricesRequest> | undefined): boolean {
    return proto3.util.equals(StreamPricesRequest, a, b);
  }
}

/**
 * Real-time price update
 *
 * @generated from message crypto_stream.PriceUpdate
 */
export class PriceUpdate extends Message<PriceUpdate> {
  /**
   * @generated from field: string ticker = 1;
   */
  ticker = "";

  /**
   * @generated from field: string price = 2;
   */
  price = "";

  /**
   * @generated from field: int64 timestamp = 3;
   */
  timestamp = protoInt64.zero;

  /**
   * Will be "BINANCE" 
   *
   * @generated from field: string exchange = 4;
   */
  exchange = "";

  /**
   * @generated from field: bool removed = 5;
   */
  removed = false;

  constructor(data?: PartialMessage<PriceUpdate>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.PriceUpdate";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ticker", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "exchange", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "removed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PriceUpdate {
    return new PriceUpdate().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PriceUpdate {
    return new PriceUpdate().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PriceUpdate {
    return new PriceUpdate().fromJsonString(jsonString, options);
  }

  static equals(a: PriceUpdate | PlainMessage<PriceUpdate> | undefined, b: PriceUpdate | PlainMessage<PriceUpdate> | undefined): boolean {
    return proto3.util.equals(PriceUpdate, a, b);
  }
}

/**
 * Ticker info with price data
 *
 * @generated from message crypto_stream.TickerInfo
 */
export class TickerInfo extends Message<TickerInfo> {
  /**
   * @generated from field: string symbol = 1;
   */
  symbol = "";

  /**
   * @generated from field: string current_price = 2;
   */
  currentPrice = "";

  /**
   * @generated from field: string last_updated = 3;
   */
  lastUpdated = "";

  constructor(data?: PartialMessage<TickerInfo>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.TickerInfo";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "symbol", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "current_price", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_updated", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TickerInfo {
    return new TickerInfo().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TickerInfo {
    return new TickerInfo().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TickerInfo {
    return new TickerInfo().fromJsonString(jsonString, options);
  }

  static equals(a: TickerInfo | PlainMessage<TickerInfo> | undefined, b: TickerInfo | PlainMessage<TickerInfo> | undefined): boolean {
    return proto3.util.equals(TickerInfo, a, b);
  }
}

/**
 * Returns TickerInfo objects
 *
 * @generated from message crypto_stream.GetActiveTickersResponse
 */
export class GetActiveTickersResponse extends Message<GetActiveTickersResponse> {
  /**
   * @generated from field: repeated crypto_stream.TickerInfo tickers = 1;
   */
  tickers: TickerInfo[] = [];

  constructor(data?: PartialMessage<GetActiveTickersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "crypto_stream.GetActiveTickersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tickers", kind: "message", T: TickerInfo, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetActiveTickersResponse {
    return new GetActiveTickersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetActiveTickersResponse {
    return new GetActiveTickersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetActiveTickersResponse {
    return new GetActiveTickersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetActiveTickersResponse | PlainMessage<GetActiveTickersResponse> | undefined, b: GetActiveTickersResponse | PlainMessage<GetActiveTickersResponse> | undefined): boolean {
    return proto3.util.equals(GetActiveTickersResponse, a, b);
  }
}

