// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file proto/crypto-stream.proto (package crypto_stream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddTickerRequest, AddTickerResponse, GetActiveTickersRequest, GetActiveTickersResponse, PriceUpdate, RemoveTickerRequest, RemoveTickerResponse, StreamPricesRequest } from "./crypto-stream_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service for managing cryptocurrency price streaming
 *
 * @generated from service crypto_stream.CryptoStreamService
 */
export const CryptoStreamService = {
  typeName: "crypto_stream.CryptoStreamService",
  methods: {
    /**
     * Add a ticker to start receiving price updates
     *
     * @generated from rpc crypto_stream.CryptoStreamService.AddTicker
     */
    addTicker: {
      name: "AddTicker",
      I: AddTickerRequest,
      O: AddTickerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Remove a ticker to stop receiving price updates
     *
     * @generated from rpc crypto_stream.CryptoStreamService.RemoveTicker
     */
    removeTicker: {
      name: "RemoveTicker",
      I: RemoveTickerRequest,
      O: RemoveTickerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stream real-time price updates
     *
     * @generated from rpc crypto_stream.CryptoStreamService.StreamPrices
     */
    streamPrices: {
      name: "StreamPrices",
      I: StreamPricesRequest,
      O: PriceUpdate,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Get list of currently active tickers
     *
     * @generated from rpc crypto_stream.CryptoStreamService.GetActiveTickers
     */
    getActiveTickers: {
      name: "GetActiveTickers",
      I: GetActiveTickersRequest,
      O: GetActiveTickersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

